feat: add AAD support in aes gcm
openresty/lua-resty-string pull request #101
Opened 2024-02-01 01:55 UTC by wzxjohn

#98

2024-02-01 01:57 UTC, wzxjohn commented
@zhuizhuhaomeng Sorry for accidentally merge the master into patch. I close the old PR and start this new one.

2024-02-01 09:10 UTC, wzxjohn commented
@zhuizhuhaomeng test case added

2024-02-01 10:27 UTC, zhuizhuhaomeng requested changes

2024-02-01 10:27 UTC, zhuizhuhaomeng commented on t/aes.t
> +
request three blank lines here.

2024-02-01 10:28 UTC, zhuizhuhaomeng requested changes

2024-02-01 10:28 UTC, zhuizhuhaomeng commented on lib/resty/aes.lua
> +    end
```suggestion
    if self._cipher == "gcm" and aad ~= nil then
        if C.EVP_EncryptUpdate(ctx, nil, tmp_len, aad, #aad) == 0 then
            return nil, "C.EVP_EncryptUpdate failed"
        end
    end
```

2024-02-01 10:28 UTC, zhuizhuhaomeng commented on lib/resty/aes.lua
> +    end
```suggestion
    if self._cipher == "gcm" and aad ~= nil then
            if C.EVP_DecryptUpdate(ctx, nil, tmp_len, aad, #aad) == 0 then
                return nil, "C.EVP_DecryptUpdate failed"
            end
    end
```

2024-02-05 07:52 UTC, closed without merging

2024-02-05 07:52 UTC, zhuizhuhaomeng commented
merge with small modification.